@extends('layouts.header')

{{-- title section --}}
@section('title')
    Excel Export
@endsection

{{-- body section --}}
@section('content')
    <div style="background: #e3f2fd; padding: 20px; margin-top: 30px">
        <h3>Instructions</h3><hr>
         <p><strong>Assignment : </strong>Using laravel develop an excel upload system to store random data generated by you for over 100k data. The fields should contain First Name, Last Name, Email and Telephone. To be submitted in 48hours.
         </p>
         <div class="row">
             <div class="col-sm-6">
                 <div style="padding: 20px">
                     <strong>Steps to run this application.</strong>
                     <p>I built the application using queue/job method. I used this method because its one of the best way to develop time consuming project of this kind. And its always a good practice not to keep application users waiting waitng while uploading. So I jobbed it.</p>
                     <ol>
                        <li>Create a <strong>database</strong> e.g excelupload</li>
                         <li>Run <strong>php artisan migrate</strong> to create models</li>
                         <li>update .env variable from QUEUE_CONNECTION=sync to <strong>QUEUE_CONNECTION=database</strong></li>
                         <li>Click on "Upload an Excel Doc" menu to download a sample document</li>
                     </ol>
                 </div>
             </div>
             <div class="col-sm-6">
                 <div style="padding: 20px">
                    <strong>How to Use</strong>
                     <ol>
                         <li>Click on "Upload an Excel Doc" menu on the navbar</li>
                         <li>Click on download sample template</li>
                         <li>Upload the downloaded file</li>
                         <li>Open a new command terminal</li>
                         <li>Navigate to the project folder on the terminal</li>
                         <li>run php artisan queue:work to proccess the jobs table.</li>
                     </ol>
                     <br><br>
                     <strong>Package Used</strong>
                     <ol>
                         <li>Laravel Excel</li>
                         <li>Bootstrap framework</li>
                     </ol>
                 </div>
             </div>
         </div>
    </div>
@endsection

